-- schema.sql
-- PostgreSQL schema for the generated World Cup Analytics CSV files.
--
-- The column order mirrors:
--   data/processed/matches_features.csv
--   data/processed/team_level.csv
-- so the README \copy commands can load the files without transformation.

DROP VIEW IF EXISTS world_cup_matches_2002_2022;
DROP TABLE IF EXISTS team_matches CASCADE;
DROP TABLE IF EXISTS matches CASCADE;

CREATE TABLE matches (
    match_id                    INTEGER PRIMARY KEY,
    date                        DATE NOT NULL,
    home_team                   TEXT NOT NULL,
    away_team                   TEXT NOT NULL,
    home_score                  INTEGER NOT NULL CHECK (home_score >= 0),
    away_score                  INTEGER NOT NULL CHECK (away_score >= 0),
    tournament                  TEXT NOT NULL,
    city                        TEXT,
    country                     TEXT,
    neutral                     BOOLEAN NOT NULL,
    year                        INTEGER NOT NULL,
    decade                      INTEGER NOT NULL,
    total_goals                 INTEGER NOT NULL CHECK (total_goals >= 0),
    goal_difference             INTEGER NOT NULL,
    absolute_goal_difference    INTEGER NOT NULL CHECK (absolute_goal_difference >= 0),
    match_result                TEXT NOT NULL CHECK (match_result IN ('home_win', 'away_win', 'draw')),
    is_draw                     BOOLEAN NOT NULL,
    home_win                    BOOLEAN NOT NULL,
    away_win                    BOOLEAN NOT NULL,
    winner                      TEXT,
    loser                       TEXT,
    dominant_win                BOOLEAN NOT NULL,
    neutral_match               BOOLEAN NOT NULL,
    is_world_cup                BOOLEAN NOT NULL,
    world_cup_year              INTEGER,
    tournament_category         TEXT NOT NULL
);

CREATE INDEX idx_matches_date ON matches (date);
CREATE INDEX idx_matches_tournament ON matches (tournament);
CREATE INDEX idx_matches_is_world_cup ON matches (is_world_cup, world_cup_year);

-- One row per team per match, generated by src/feature_engineering.py.
CREATE TABLE team_matches (
    match_id             INTEGER NOT NULL REFERENCES matches (match_id),
    date                 DATE NOT NULL,
    team                 TEXT NOT NULL,
    opponent             TEXT NOT NULL,
    tournament           TEXT NOT NULL,
    tournament_category  TEXT NOT NULL,
    home_or_away         TEXT NOT NULL CHECK (home_or_away IN ('home', 'away')),
    neutral              BOOLEAN NOT NULL,
    goals_for            INTEGER NOT NULL CHECK (goals_for >= 0),
    goals_against        INTEGER NOT NULL CHECK (goals_against >= 0),
    is_world_cup         BOOLEAN NOT NULL,
    world_cup_year       INTEGER,
    year                 INTEGER NOT NULL,
    goal_difference      INTEGER NOT NULL,
    result               TEXT NOT NULL CHECK (result IN ('win', 'draw', 'loss')),
    win                  BOOLEAN NOT NULL,
    draw                 BOOLEAN NOT NULL,
    loss                 BOOLEAN NOT NULL,
    points               INTEGER NOT NULL CHECK (points IN (0, 1, 3)),
    dominant_win         BOOLEAN NOT NULL,
    PRIMARY KEY (match_id, team)
);

CREATE INDEX idx_team_matches_team ON team_matches (team);
CREATE INDEX idx_team_matches_wc ON team_matches (is_world_cup, world_cup_year);

-- Convenience view: FIFA men's World Cup final-tournament matches, 2002-2022 only.
CREATE OR REPLACE VIEW world_cup_matches_2002_2022 AS
SELECT *
FROM matches
WHERE is_world_cup = TRUE
  AND world_cup_year BETWEEN 2002 AND 2022;
